[window]
decorations = "None"
opacity = 0.95
blur = true

[font]
normal = { family =  "FiraCode", style = "Medium" }
size = 10.5

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
 { key = "N", mods = "Control|Shift",  action = "SpawnNewInstance" },
 { key = "-", mods = "Control",  action = "DecreaseFontSize" },
 { key = "0", mods = "Control",  action = "ResetFontSize" },
 { key = "+", mods = "Control|Shift",  action = "IncreaseFontSize" },
 { key = "c", mods = "Control|Shift",  action = "Copy" },
 { key = "v", mods = "Control|Shift",  action = "Paste" },
 { key = "F11", action = "ToggleFullscreen" },

]

[colors]
draw_bold_text_with_bright_colors = true

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'
